# Generated by Django 3.0.6 on 2021-03-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Мой праздник', 'verbose_name_plural': 'Мои праздники'},
        ),
    ]
