# Generated by Django 3.0.6 on 2021-02-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Мое желание')),
                ('photo', models.ImageField(upload_to='wish_pic/', verbose_name='Фото моего желания')),
                ('link_to_wish', models.URLField(verbose_name='Ссылка на желание')),
                ('status', models.CharField(choices=[('gifted', 'Подарено'), ('waiting', 'В ожидании'), ('reserved', 'Забронировано')], default='waiting', max_length=50, verbose_name='Статус подарка')),
            ],
        ),
        migrations.AddField(
            model_name='giftmeuser',
            name='wish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='giftme.Wish'),
        ),
    ]
