# Generated by Django 3.0.6 on 2021-02-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0003_auto_20210216_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Мое желание', 'verbose_name_plural': 'Мои желания'},
        ),
    ]
