# Generated by Django 3.0.6 on 2021-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0004_auto_20210216_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('gifted', 'Подарено'), ('reserved', 'Забронировано')], default='waiting', max_length=50, verbose_name='Статус подарка'),
        ),
    ]
