# Generated by Django 3.0.6 on 2021-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_me_my', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_holiday', models.CharField(max_length=30, verbose_name='Название праздника')),
                ('date_of_holiday', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
        ),
    ]
